---
dependencies: []

galaxy_info:
  role_name: mysql
  author: TeeHem
  description: MySQL server for RHEL/CentOS and Debian/Ubuntu.
  company: "TeeHem inc"
  license: "Private property TeeHem"
  min_ansible_version: 2.10
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Archlinux
      versions:
        - all
  galaxy_tags:
    - database
    - mysql
    - mariadb
    - db
    - sql
